### ISSUE TITLE
代码跑不起来,引入的库`frusty_logger`,提示不存在？

### ISSUE THREAD

**Issue by Aaron009** [yiv/full_search#1]
```shell
frusty_logger:
  git:
    url: https://github.com/sunshine-protocol/frusty-logger.git
```

对不起，这个问题，能删掉吗？好像是网络问题，我关掉重新打开又可以了。

**Comment by IWANABETHATGUY** [comment]
你自己close 以下就好了， 评论旁边

**Comment by Aaron009** [comment]
> 你自己close 以下就好了， 评论旁边

我以为是作者，我还遇到其他问题了呢，给他邮件了，等待他回信。

你会Rust Flutter FFI吗？
我遇到一个问题，帮我看看呗？
https://github.com/dart-lang/ffi/issues/75

**Comment by yiv** [comment]
> By default, XCode will skip bundling the libexample.a library if it detects that it is not being used. To force its inclusion, add dummy invocations in SwiftMylibPlugin.swift that use every single native function that you use from Flutter:

需要把每个每个 ffi 提供的函数在 SwiftMylibPlugin.swift 显性地调用，只调用一个，IOS 在 debug 下能正常工作，但是到了 IOS releas 模式，*.a 静态库里的所有未被调用的符号都会被丢弃，所以在跑起来的时候出现找不到 symbol
